# Generated by Django 4.1.8 on 2023-04-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availableBalanceBTC',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balanceBTC',
            field=models.FloatField(default=7),
        ),
    ]
