# Generated by Django 4.1.8 on 2023-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_availablebalancebtc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sellingPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='availableBalanceBTC',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balanceBTC',
            field=models.FloatField(default=0),
        ),
    ]
