# Generated by Django 4.1.8 on 2023-04-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_sellingprice_alter_profile_availablebalancebtc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sellingPrice',
            new_name='realTotalPrice',
        ),
    ]
