# Generated by Django 4.1.8 on 2023-04-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_realtotalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='realTotalPrice',
            new_name='totalPriceExecuted',
        ),
    ]
