# Generated by Django 4.1.8 on 2023-04-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_realtotalprice_order_totalpriceexecuted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
